import type { CSSProperties } from "react";

type ThemeVariableMap = Record<`--${string}`, string>;

const sizing = {
  containerWidth: 1180,
  sectionY: "clamp(4rem, 7vw, 6rem)",
  sectionYMobile: "clamp(3rem, 9vw, 4rem)",
  containerX: "clamp(1rem, 3vw, 1.5rem)",
  gridGap: "clamp(1rem, 1.8vw, 1.35rem)",
  cardPadding: "clamp(1rem, 2vw, 1.35rem)",
  radii: {
    sm: "12px",
    md: "18px",
    lg: "26px",
    xl: "38px",
    pill: "999px",
  },
} as const;

export const ethiopiaTheme = {
  name: "ethiopia-highland-premium",
  color: {
    bg: "#060907",
    bgTop: "#0d140e",
    bgDeep: "#020302",
    foreground: "#f6f3ea",
    foregroundSoft: "#d8cfba",
    muted: "#9c9486",
    primary: "#168a54",
    primarySoft: "rgba(22, 138, 84, 0.18)",
    primaryStrong: "#1ec06f",
    secondary: "#d6a33d",
    tertiary: "#7b1f27",
    surface: "rgba(11, 19, 14, 0.82)",
    surfaceStrong: "rgba(19, 30, 22, 0.96)",
    surfaceAccent: "rgba(20, 56, 35, 0.9)",
    surfaceMedia: "rgba(12, 20, 15, 0.94)",
    borderSoft: "rgba(214, 163, 61, 0.16)",
    borderStrong: "rgba(214, 163, 61, 0.4)",
    gridLine: "rgba(255, 244, 216, 0.06)",
    glow: "rgba(214, 163, 61, 0.28)",
    headerSurface: "rgba(8, 15, 11, 0.74)",
    headerBorder: "rgba(214, 163, 61, 0.18)",
    headerShadow: "0 24px 60px rgba(0, 0, 0, 0.35)",
    footerSurface: "rgba(8, 15, 11, 0.9)",
    footerBorder: "rgba(22, 138, 84, 0.24)",
    cardSurface: "rgba(11, 20, 15, 0.86)",
    cardSurfaceStrong: "rgba(18, 31, 22, 0.98)",
    cardBorder: "rgba(246, 243, 234, 0.08)",
    mediaSurface: "rgba(8, 17, 12, 0.94)",
    buttonBg: "linear-gradient(135deg, #d6a33d 0%, #f2cb75 52%, #c58722 100%)",
    buttonFg: "#10120d",
    buttonBorder: "rgba(255, 245, 221, 0.22)",
  },
  type: {
    display: "clamp(3.1rem, 8vw, 5.6rem)",
    heading: "clamp(2rem, 4vw, 3.25rem)",
    subheading: "clamp(1.05rem, 2vw, 1.25rem)",
    cardTitle: "clamp(1.2rem, 2vw, 1.45rem)",
    bodyLg: "clamp(1.02rem, 1.8vw, 1.14rem)",
    body: "1rem",
    label: "0.84rem",
    meta: "0.76rem",
    metric: "clamp(1.5rem, 3vw, 2.2rem)",
    metricSecondary: "0.92rem",
    stat: "clamp(1.05rem, 2vw, 1.25rem)",
  },
  radius: sizing.radii,
  space: {
    sectionY: sizing.sectionY,
    sectionYMobile: sizing.sectionYMobile,
    containerX: sizing.containerX,
    cardPadding: sizing.cardPadding,
    gridGap: sizing.gridGap,
  },
  shadow: {
    soft: "0 12px 38px rgba(0, 0, 0, 0.2)",
    card: "0 22px 48px rgba(0, 0, 0, 0.28)",
    hero: "0 40px 90px rgba(0, 0, 0, 0.42)",
    glow: "0 0 60px rgba(214, 163, 61, 0.18)",
  },
  motion: {
    durationFast: 220,
    durationBase: 420,
    durationSlow: 760,
    durationLoop: 5400,
    easingStandard: "easeOutCubic",
    easingEntrance: "cubicBezier(0.22, 1, 0.36, 1)",
    easingEmphasis: "easeOutExpo",
  },
} as const;

const themeVariables: ThemeVariableMap = {
  "--color-bg": ethiopiaTheme.color.bg,
  "--color-bg-top": ethiopiaTheme.color.bgTop,
  "--color-bg-deep": ethiopiaTheme.color.bgDeep,
  "--color-foreground": ethiopiaTheme.color.foreground,
  "--color-foreground-soft": ethiopiaTheme.color.foregroundSoft,
  "--color-muted": ethiopiaTheme.color.muted,
  "--color-primary": ethiopiaTheme.color.primary,
  "--color-primary-soft": ethiopiaTheme.color.primarySoft,
  "--color-primary-strong": ethiopiaTheme.color.primaryStrong,
  "--color-secondary": ethiopiaTheme.color.secondary,
  "--color-tertiary": ethiopiaTheme.color.tertiary,
  "--color-surface": ethiopiaTheme.color.surface,
  "--color-surface-strong": ethiopiaTheme.color.surfaceStrong,
  "--color-surface-accent": ethiopiaTheme.color.surfaceAccent,
  "--color-surface-media": ethiopiaTheme.color.surfaceMedia,
  "--color-border-soft": ethiopiaTheme.color.borderSoft,
  "--color-border-strong": ethiopiaTheme.color.borderStrong,
  "--color-grid-line": ethiopiaTheme.color.gridLine,
  "--color-glow": ethiopiaTheme.color.glow,
  "--header-surface": ethiopiaTheme.color.headerSurface,
  "--header-border": ethiopiaTheme.color.headerBorder,
  "--header-shadow": ethiopiaTheme.color.headerShadow,
  "--footer-surface": ethiopiaTheme.color.footerSurface,
  "--footer-border": ethiopiaTheme.color.footerBorder,
  "--card-surface": ethiopiaTheme.color.cardSurface,
  "--card-surface-strong": ethiopiaTheme.color.cardSurfaceStrong,
  "--card-border": ethiopiaTheme.color.cardBorder,
  "--media-surface": ethiopiaTheme.color.mediaSurface,
  "--button-bg": ethiopiaTheme.color.buttonBg,
  "--button-fg": ethiopiaTheme.color.buttonFg,
  "--button-border": ethiopiaTheme.color.buttonBorder,
  "--container-width": `${sizing.containerWidth}px`,
  "--section-y": ethiopiaTheme.space.sectionY,
  "--section-y-mobile": ethiopiaTheme.space.sectionYMobile,
  "--container-x": ethiopiaTheme.space.containerX,
  "--grid-gap": ethiopiaTheme.space.gridGap,
  "--card-padding": ethiopiaTheme.space.cardPadding,
  "--radius-sm": ethiopiaTheme.radius.sm,
  "--radius-md": ethiopiaTheme.radius.md,
  "--radius-lg": ethiopiaTheme.radius.lg,
  "--radius-xl": ethiopiaTheme.radius.xl,
  "--radius-pill": ethiopiaTheme.radius.pill,
  "--shadow-soft": ethiopiaTheme.shadow.soft,
  "--shadow-card": ethiopiaTheme.shadow.card,
  "--shadow-hero": ethiopiaTheme.shadow.hero,
  "--shadow-glow": ethiopiaTheme.shadow.glow,
  "--font-display": "\"Arial Narrow\", \"Segoe UI\", Tahoma, sans-serif",
  "--font-body": "\"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif",
  "--type-display": ethiopiaTheme.type.display,
  "--type-heading": ethiopiaTheme.type.heading,
  "--type-subheading": ethiopiaTheme.type.subheading,
  "--type-card-title": ethiopiaTheme.type.cardTitle,
  "--type-body-lg": ethiopiaTheme.type.bodyLg,
  "--type-body": ethiopiaTheme.type.body,
  "--type-label": ethiopiaTheme.type.label,
  "--type-meta": ethiopiaTheme.type.meta,
  "--type-metric": ethiopiaTheme.type.metric,
  "--motion-fast": `${ethiopiaTheme.motion.durationFast}ms`,
  "--motion-base": `${ethiopiaTheme.motion.durationBase}ms`,
  "--motion-slow": `${ethiopiaTheme.motion.durationSlow}ms`,
  "--motion-loop": `${ethiopiaTheme.motion.durationLoop}ms`,
};

export const getEthiopiaThemeStyle = (): CSSProperties =>
  themeVariables as unknown as CSSProperties;
